# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ General-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
general-config: 

  autoplug: 
    # Stops AutoPlug when your server stops. Enabling this feature is not recommended.
    auto-stop: false

  server: 
    # Enter your Server-Key here. You get it by registering yourself and your server on https://autoplug.one.
    # The Server-Key enables remote access from your account.
    # No matter what, keep this key private to ensure your servers security!
    key: NO_KEY
    # Starts your server with the start of AutoPlug.
    auto-start: true
    # Creates an eula.txt file if not existing and accepts it.
    auto-eula: true
    # The full command used to start your server.
    # Like 'java -jar server.jar' for example. Or './server.exe'.
    # The working directory is where the AutoPlug-Client.jar is located in.
    start-command: java -Xms512M -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar nogui
    # AutoPlug uses this command to stop your server.
    stop-command: stop
    restart-on-crash: true

  directory-cleaner: 
    # Deletes files older than 'max-days' in the selected directories.
    enabled: true
    # If the file is older than the provided time in days, it gets deleted.
    max-days: 7
    # The list of directories to clean.
    # By default sub-directories will not get cleaned, unless you add 'true' before its path, like shown below.
    # Supported paths are relative (starting with './' which is the servers root directory) and absolute paths.
    list: 
      - true ./autoplug/logs
      - ./autoplug/downloads
