# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Shared-Files-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
shared-files-config: 
  # Enable/Disable sharing folders from this server to other servers.
  # NOTE: CHANGES TO THIS FILE REQUIRE A AUTOPLUG RESTART TO TAKE AFFECT!
  enable: false
  # List of folders to watch. Once a file event happens, that event/change gets shared/sent to the servers in the 'send-to' list.
  # All folders must be sub-folders of the server root and thus start with './' (the servers root directory).
  # If you want to watch all files from your server simply add './' below.
  # Note that sub-folders of the added folders below are also watched. 
  copy-from: 
    - ./plugins
    - ./server.jar
  # List of server root folders of the servers which receive the file changes.
  # Note that absolute and relative paths are supported.
  send-to: 
    - C:\User\Peter\servers\my-second-server # Example for absolute path
    - ./servers/another-server # Example for relative path
