# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Tasks-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
tasks-config: 

  live-tasks: 
    # Enable this to view the detailed progress of a task. Supported platforms: Windows, Linux, OS X, Solaris and FreeBSD.
    # Enabling this on unsupported platform will result in console spam.
    enable: true
    # Refresh interval in milliseconds.
    # How often a task should get refreshed and update its information. Default is: 250ms
    refresh-interval: 250

  # If the tasks produced warnings, these get shown.
  # Its recommended to keep this option enabled.
  show-warnings: true
  # Shows additional, debugging information related to the warning.
  # If the warning is an exception, its stack trace gets printed.
  # The same information is available in the log file.
  # Note that the 'show-warnings' option above must be enabled too.
  show-detailed-warnings: false
