# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Web-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
#  
# #######################################################################################################################
# Note: Changes to this file probably require you to enter '.con reload' to have affect.
web-config: 
  # Sends recent log messages (and future messages) to the Online-Console and can receive commands from it.
  # To have as little impact on your server as possible, this only happens when you are logged in.
  online-console: true
  updater-results: 
    # Sends the plugins-updaters results to AutoPlug-Web.
    # By disabling this, you won't be able to see a summary of the updaters result online anymore.
    send-plugins-updaters-results: true
    send-server-updaters-results: true
    send-self-updaters-results: true
  send-details: 
    # Sent information:
    # - Server status (is it running/online or not)
    # - Player count
    # This connection stays always active.
    public: true
    # Sent information:
    # - CPU maximum and current speeds
    # - Memory maximum size and currently used size
    # This connection is only active when logged in.
    private: true
    # The ip-address from where to retrieve server details, like MOTD, player count etc.
    ip: 127.0.0.1
    # The port from where to retrieve server details. Gets automatically detected on start. If that fails you get a warning.
    port: 
  # Establishes the connection, once you are logged in to AutoPlug-Web.
  # Enables you to manage this servers files from AutoPlugs' web panel.
  file-manager: true
